### ISSUE TITLE
Epic: English translation of documentation

### ISSUE THREAD

**Issue by duckfullstop** [evcc-io/docs#424]
A large number of users from countries that speak English (either natively or as a major language) use evcc, and rely on translating the documentation using Google Translate or other machine learning tools. However, this results in a number of issues and bad translations (especially surrounding configuration blocks).

This Epic targets a full British English translation of the documentation.

Steps to take:

* [x] Activate i18n mode in Docusaurus
  * https://github.com/evcc-io/docs/pull/420
* [x] Translate root pages including home and sponsorships
  * https://github.com/evcc-io/docs/pull/420
* [x] Translate Installation section
  * https://github.com/evcc-io/docs/pull/421
* [x] Translate Guides (tips & FAQ) section
  * https://github.com/evcc-io/docs/pull/426
* [x] Translate Reference section 
  * https://github.com/evcc-io/docs/pull/425
* [x] Set up generation of devices section
  * https://github.com/evcc-io/docs/issues/429
  * https://github.com/evcc-io/docs/issues/432
* [x] Remove references to DE only in project description **needs organisation manager**
* [x] Capture new English images (screenshots, etc)
  * https://github.com/evcc-io/docs/issues/422
    * Closed by https://github.com/evcc-io/docs/pull/503

**Comment by naltatis** [comment]
Some pages still need translation. But I think the epic is done. Thanks @duckfullstop for pushing this 🙌
